### ISSUE TITLE
Research and Make Game Plan for Quest Multiplayer

### ISSUE THREAD

**Issue by SonicKurt** [SonicKurt/EuchreVR#2]
Research into how Unreal Engine does multiplayer with multiple avatars (players):

- These avatars should incorporate online connections with Quests. We need to determine whether a Quest needs to be a server and whether the other Quests are clients connecting to the server.  If not, determine how we set up a server on a computer and have all the clients connect to it.
- Find a way to get their Metaverse avatar.

**Comment by SebastianNeiswanger** [comment]
Maybe also look at utilizing the quest avatars

**Comment by SonicKurt** [comment]
We cannot pull the user's Meta avatar due to them not updating the extension yet for it. It is only available for Unity at the moment. As a result, we will have to use UE avatars! I listed a link to their depreciated avatar plugin.

https://developer.oculus.com/documentation/unreal/as-avatars-sdk-intro/
